# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainfest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emainfest.proto\x12\x03sfs\"B\n\x04\x46ile\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x0e\n\x06Offset\x18\x02 \x01(\x04\x12\x0c\n\x04Size\x18\x03 \x01(\x04\x12\x10\n\x08Metadata\x18\x04 \x01(\x0c\"$\n\x08Mainfest\x12\x18\n\x05\x46iles\x18\x01 \x03(\x0b\x32\t.sfs.File')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mainfest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILE._serialized_start=23
  _FILE._serialized_end=89
  _MAINFEST._serialized_start=91
  _MAINFEST._serialized_end=127
# @@protoc_insertion_point(module_scope)
